# Generated by Django 4.0.3 on 2022-03-23 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrls',
            fields=[
                ('short_url', models.SlugField(primary_key=True, serialize=False, verbose_name='Короткая ссылка')),
                ('full_url', models.CharField(max_length=60, verbose_name='Длинная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('qr_code', models.ImageField(upload_to='photos/qr/%Y/%m/%d/', verbose_name='QR-код')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
