# Generated by Django 4.0.3 on 2022-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_shorturls_qr_code_alter_shorturls_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество переходов'),
        ),
        migrations.AlterField(
            model_name='shorturls',
            name='full_url',
            field=models.CharField(max_length=255, verbose_name='Длинная ссылка'),
        ),
    ]
